# Copyright (c) 2026, Tamir Levin.
# SPDX-License-Identifier: Apache-2.0
"""AUTO-GENERATED by scripts/check_workspace.py --emit-table -- DO NOT HAND-EDIT.

Measured reachable EE envelope of the closed 5-bar, as world-z bins with
the y-interval reachable at that height (valid, settled samples only;
row i intersected with row i+1 to stay conservative). Regenerate with:

    ~/isaac/IsaacLab/isaaclab.sh -p scripts/check_workspace.py \
        --grid 151 \
        --limit-left -1.2217304764 0.7853981634 \
        --limit-right -0.7853981634 1.2217304764 \
        --arm-low -1.4835298642 --arm-high 1.4835298642 \
        --emit-table
"""

ELBOW_BOUNDS_LEFT = (-1.2217304764, 0.7853981634)
ELBOW_BOUNDS_RIGHT = (-0.7853981634, 1.2217304764)
GRID = 151
Z_STEP = 0.01
ARM_JOINT_RANGE_RAD = (-1.4827, 1.4827)
# rows: (z_lo_world, z_hi_world, y_min, y_max)
TABLE = [
    (0.110, 0.120, -0.4478, 0.4478),
    (0.120, 0.130, -0.4558, 0.4558),
    (0.130, 0.140, -0.4636, 0.4636),
    (0.140, 0.150, -0.4711, 0.4712),
    (0.150, 0.160, -0.4785, 0.4785),
    (0.160, 0.170, -0.4857, 0.4857),
    (0.170, 0.180, -0.4926, 0.4926),
    (0.180, 0.190, -0.4993, 0.4993),
    (0.190, 0.200, -0.5058, 0.5058),
    (0.200, 0.210, -0.5120, 0.5120),
    (0.210, 0.220, -0.5180, 0.5181),
    (0.220, 0.230, -0.5238, 0.5238),
    (0.230, 0.240, -0.5294, 0.5294),
    (0.240, 0.250, -0.5348, 0.5348),
    (0.250, 0.260, -0.5256, 0.5256),
    (0.260, 0.270, -0.4771, 0.4771),
    (0.270, 0.280, -0.4411, 0.4412),
    (0.280, 0.290, -0.4128, 0.4128),
    (0.290, 0.300, -0.4128, 0.4128),
]
